// The FAB's position (bottom:24px;right:24px) is hardcoded in Botpress's own
// shadow-scoped stylesheet, not exposed as a CSS custom property, so
// page-level CSS can never reach it - the shadow root itself is open, so we
// inject our own override style directly into it instead, to move it away
// from our own #contact-icon button in the same corner, vertically centered
// on the navbar. Botpress rebuilds the shadow root's contents at least once
// after its own init settles, wiping out a one-shot injection, so a
// persistent observer keeps re-applying the override style whenever it goes
// missing. The navbar's own height shifts (.scrolled shrinks its padding),
// so the offset is recomputed - fixed pixels drift out of center between
// the two states - on every re-apply and on navbar resize.
// The same style also recolors the button (--main) and its icon (--white) with
// the site's colors, which custom properties carry into the shadow root
// (page-level CSS can't reach it).
const BP_FAB_OVERRIDE_ID = 'bp-fab-position-override';
const BP_FAB_OVERRIDE_CSS = top => `.bpFabWrapper { bottom: auto !important; top: ${top}px !important; right: 20px !important; } .bpFabContainer { background-color: var(--main) !important; } .bpFabIcon { background-color: var(--white) !important; }`;

function watchBotpressFab(shadowRoot) {
	function applyOverride() {
		const fab = shadowRoot.querySelector('.bpFabWrapper');
		const navbar = document.getElementById('ftco-navbar');
		const fabHeight = fab ? fab.getBoundingClientRect().height : 64;
		const navHeight = navbar ? navbar.getBoundingClientRect().height : 85;
		const top = Math.round((navHeight - fabHeight) / 2);
		const css = BP_FAB_OVERRIDE_CSS(top);
		const existing = shadowRoot.getElementById(BP_FAB_OVERRIDE_ID);
		// Writing textContent (even to the same value) is itself a childList
		// mutation the observer below is watching for - skipping no-op writes
		// keeps a stable navbar height from re-triggering itself forever.
		if (existing) {
			if (existing.textContent !== css) {
				existing.textContent = css;
			}
			return;
		}
		const style = document.createElement('style');
		style.id = BP_FAB_OVERRIDE_ID;
		style.textContent = css;
		shadowRoot.appendChild(style);
	}
	applyOverride();
	// subtree:false - only shadowRoot's own direct children (Botpress rebuilding
	// its top-level UI). subtree:true would also fire on every unrelated internal
	// mutation Botpress makes while running, each forcing a synchronous layout
	// via getBoundingClientRect above - enough volume to freeze the tab.
	new MutationObserver(applyOverride).observe(shadowRoot, { childList: true });
	const navbar = document.getElementById('ftco-navbar');
	if (navbar) {
		new ResizeObserver(applyOverride).observe(navbar);
	}
}

function loadBotpress() {
	const script = document.createElement('script');
	script.src = 'https://cdn.botpress.cloud/webchat/v3.7/inject.js';
	script.integrity = 'sha384-rIz8hhxDTms5tHY2DgfjlCHykKqWkDUXz06Qy4BCWj5iTYn2btB2cBPhJlaQQ7JR';
	script.crossOrigin = 'anonymous';
	script.onload = function () {
		// Bot-specific config, regenerated by Botpress whenever the dashboard
		// settings change - no SRI here since pinning a hash would break on
		// their next update. Only appended once window.botpress.init exists,
		// since two dynamically-inserted scripts execute in whichever order
		// they finish downloading, not insertion order.
		const config = document.createElement('script');
		config.src = 'https://files.bpcontent.cloud/2025/10/06/10/20251006102232-ANM8U0DA.js';
		document.head.appendChild(config);

		// #fab-root doesn't exist until the config script's own async init
		// finishes, so watch for it instead of guessing a fixed delay.
		const fabRoot = document.getElementById('fab-root');
		if (fabRoot?.shadowRoot) {
			watchBotpressFab(fabRoot.shadowRoot);
			return;
		}
		const observer = new MutationObserver(function () {
			const root = document.getElementById('fab-root');
			if (root?.shadowRoot) {
				observer.disconnect();
				watchBotpressFab(root.shadowRoot);
			}
		});
		observer.observe(document.body, { childList: true, subtree: true });
	};
	document.head.appendChild(script);
}

if (window.innerWidth >= 1024) {
	const interactionEvents = ['scroll', 'click', 'mousemove'];
	const onFirstInteraction = function () {
		interactionEvents.forEach(function (event) {
			window.removeEventListener(event, onFirstInteraction);
		});
		loadBotpress();
	};
	interactionEvents.forEach(function (event) {
		window.addEventListener(event, onFirstInteraction, { once: true, passive: true });
	});
}
