function loadBotpress() {
	const script = document.createElement('script');
	script.src = 'https://cdn.botpress.cloud/webchat/v3.7/inject.js';
	script.integrity = 'sha384-rIz8hhxDTms5tHY2DgfjlCHykKqWkDUXz06Qy4BCWj5iTYn2btB2cBPhJlaQQ7JR';
	script.crossOrigin = 'anonymous';
	script.onload = function () {
		// Bot-specific config, regenerated by Botpress whenever the dashboard
		// settings change - no SRI here since pinning a hash would break on
		// their next update. Only appended once window.botpress.init exists,
		// since two dynamically-inserted scripts execute in whichever order
		// they finish downloading, not insertion order.
		const config = document.createElement('script');
		config.src = 'https://files.bpcontent.cloud/2025/10/06/10/20251006102232-ANM8U0DA.js';
		document.head.appendChild(config);
	};
	document.head.appendChild(script);
}

if (window.innerWidth >= 1024) {
	const interactionEvents = ['scroll', 'click', 'mousemove'];
	const onFirstInteraction = function () {
		interactionEvents.forEach(function (event) {
			window.removeEventListener(event, onFirstInteraction);
		});
		loadBotpress();
	};
	interactionEvents.forEach(function (event) {
		window.addEventListener(event, onFirstInteraction, { once: true, passive: true });
	});
}
