let appRoutes = {
  "home-page": "/{lng}",
  "policy": "/{lng}/policy",
  "terms": "/{lng}/terms"
};

let homeSection = "home-section";

let goHereSection = "resume-section";

let appMainSections = [
  "about-section",
  "resume-section",
  "services-section",
  "projects-section",
  "blog-section",
  "contact-section"
];

let appSubSections = [
  "education",
  "experiences",
  "skills",
  "languages",
  "awards"
];

let appAllSections = [
  homeSection,
  ...appMainSections,
  goHereSection,
  ...appSubSections
];

let appMessages = {
	"success-generic": {"fr": "L'opération a été un franc succès.", "en": "The operation was successfully completed."},
	"error-generic" : {"fr": "Oops ! Une erreur est survenue. Réessayez plus tard.", "en": "Oops ! An error has occurred. Try again later."}	
};

let xp = 4; // Years of experience
let cdiCount = 3;
let email = "nicolas.bogalheiro@gmail.com";
let city = "Lyon";

let tokenClient; // Generated by Google

let appScrollSections = []; // Completed automatically

let checkpointSubSection; // Completed automatically
 
function saveHashSession(hash) {
	sessionStorage.setItem('currentHash', hash);
}

function clearUrlPath() {
	history.replaceState(null, null, window.location.pathname);
}

function percentageToDegrees(percentage) {
	return percentage / 100 * 360;
}

function computeAge() {
	const d = new Date("1997-11-19");
	const today = new Date();
	return today.getFullYear() - d.getFullYear() - (today < new Date(today.getFullYear(), d.getMonth(), d.getDate()) ? 1 : 0);
}

function getCurrentLanguage() {
	return document.documentElement.lang;	
}

function toggleContact() {
   const contactWindow = document.getElementById('contact-window');
   if (!contactWindow.style.display || contactWindow.style.display === 'none') {
        contactWindow.style.display = 'flex';       
   } else {
        contactWindow.style.display = 'none';
   }
}

function addRedirectById(elementId) {
  const balise = document.getElementById(elementId);
  if (balise) {
    const path = appRoutes[elementId];
    balise.href = path ? path.replace('{lng}',getCurrentLanguage()) : "/en";
    balise.addEventListener('click', function() {
	  sessionStorage.clear(); // Reset hash for all other links
    });
  }
}

function loadImages(selector, extension, one = false) {
  const imgs = document.querySelectorAll(`${selector}`);
  Array.from(imgs).some((el, index) => {
	const locationImg = `images/${el.id}.${extension}`;
	if (el.tagName.toLowerCase() === 'img') {
		el.src = locationImg;
	} else {
		el.style.backgroundImage = `url(${locationImg})`;
	}
    // If first iteration, return true to stop further iteration
    return index === 0 && one;
  });
}

function getMessage(key) {
	return appMessages[key]?.[`${getCurrentLanguage()}`] || "";
}

function switchLanguage(url) {
    var newUrl = url;
    if (url.includes('/fr')) {
        newUrl = url.replace('/fr', '/en');
    } else if (url.includes('/en')) {
        newUrl = url.replace('/en', '/fr');
    }
	const currentHash = sessionStorage.getItem('currentHash');
	if(currentHash){
		newUrl += `#${currentHash}`; 
	}
    return newUrl;
}

function initTranslator() {
	const toggle = document.getElementById('language-toggle');
	if(toggle){
		toggle.checked = getCurrentLanguage() == 'fr';
		toggle.addEventListener('change', function () {
			toggle.checked = getCurrentLanguage() == 'fr';
			window.location.href = switchLanguage(window.location.href);
		});
	}
}

function initProfile() {
	$('.author').text($('meta[name="author"]').attr('content'));
	$('#city').text(city);
	$('.email').text(email);
	$('.age').text(computeAge());
	$('.xp').each(function() {
	  if ($(this).hasClass('number')) {
		$(this).attr('data-number', xp);
	  } else {
		$(this).text(xp);
	  }
	});
	$('#cdiCount').text(cdiCount);
}

AOS.init({
  duration: 800,
  easing: 'slide'
});

(function($) {
	"use strict";
	
	initProfile();
	
	$(window).stellar({
		responsive: true,
		parallaxBackgrounds: true,
		parallaxElements: true,
		horizontalScrolling: false,
		hideDistantElements: false,
		scrollProperty: 'scroll'
	});

	var fullHeight = function() {
		$('.js-fullheight').css('height', $(window).height());
		$(window).resize(function(){
			$('.js-fullheight').css('height', $(window).height());
		});
	};
	fullHeight();

	var loader = function() {
		setTimeout(function() { 
			if($('#ftco-loader').length > 0) {
				$('#ftco-loader').removeClass('show');
			}
		}, 1);
	};
	loader();

	$.Scrollax();

	var burgerMenu = function() {
		$('body').on('click', '.navbar-toggler', function(event){
			event.preventDefault();
			if ( $('#ftco-nav').is(':visible') ) {
				$(this).removeClass('active');
			} else {
				$(this).addClass('active');	
			}	
		});
	};
	burgerMenu();

	var onePageClick = function() {
		$(document).on('click', '#ftco-nav a[href^="#"]', function (event) {
			event.preventDefault();
			$('html, body').animate({
				scrollTop: $($.attr(this, 'href')).offset().top - 70
			}, 500);
		});
	};
	onePageClick();
	
	var carousel = function() {
		$('.home-slider').owlCarousel({
	    loop:true,
	    autoplay: true,
	    margin:0,
	    animateOut: 'fadeOut',
	    animateIn: 'fadeIn',
	    nav:false,
	    autoplayHoverPause: false,
	    items: 1,
	    navText : ["<span class='icon-chevron-left'></span>","<span class='icon-chevron-right'></span>"],
	    responsive:{
	      0:{
	        items:1
	      },
	      600:{
	        items:1
	      },
	      1000:{
	        items:1
	      }
	    }
		});
	};
	carousel();

	$('nav .dropdown').hover(function(){
		$(this).addClass('show');
		$(this).find('> a').attr('aria-expanded', true);
		$(this).find('.dropdown-menu').addClass('show');
	}, function(){
		$(this).removeClass('show');
		$(this).find('> a').attr('aria-expanded', false);
		$(this).find('.dropdown-menu').removeClass('show');
	});

	var scrollWindow = function() {
		$(window).scroll(function(){
			var $w = $(this), st = $w.scrollTop(), navbar = $('.ftco_navbar'), sd = $('.js-scroll-wrap');
			if (st > 150) {
				if ( !navbar.hasClass('scrolled') ) {
					navbar.addClass('scrolled');	
				}
			} 
			if (st < 150) {
				if ( navbar.hasClass('scrolled') ) {
					navbar.removeClass('scrolled sleep');
				}
			} 
			if ( st > 350 ) {
				if ( !navbar.hasClass('awake') ) {
					navbar.addClass('awake');	
				}
				if(sd.length > 0) {
					sd.addClass('sleep');
				}
			}
			if ( st < 350 ) {
				if ( navbar.hasClass('awake') ) {
					navbar.removeClass('awake');
					navbar.addClass('sleep');
				}
				if(sd.length > 0) {
					sd.removeClass('sleep');
				}
			}
			// For small screens, the header becomes dark
			if (window.scrollY <= 5) {
				document.querySelector('.off').classList.add('top-scroll');
			} else {
				document.querySelector('.off').classList.remove('top-scroll');
			}
		});
	};
	scrollWindow();

	var counter = function() {
		$('#section-counter, .hero-wrap, .ftco-counter, .ftco-about').waypoint( function( direction ) {
			if( direction === 'down' && !$(this.element).hasClass('ftco-animated') ) {
				var comma_separator_number_step = $.animateNumber.numberStepFactories.separator(',')
				$('.number').each(function(){
					var $this = $(this), num = $this.data('number');
					$this.animateNumber(
					  {
					    number: num,
					    numberStep: comma_separator_number_step
					  }, 7000
					);
				});	
			}
		} , { offset: '95%' } );
	}
	counter();

	var contentWayPoint = function() {
		var i = 0;
		$('.ftco-animate').waypoint( function( direction ) {
			if( direction === 'down' && !$(this.element).hasClass('ftco-animated') ) {
				i++;
				$(this.element).addClass('item-animate');
				setTimeout(function(){
					$('body .ftco-animate.item-animate').each(function(k){
						var el = $(this);
						setTimeout( function () {
							var effect = el.data('animate-effect');
							if ( effect === 'fadeIn') {
								el.addClass('fadeIn ftco-animated');
							} else if ( effect === 'fadeInLeft') {
								el.addClass('fadeInLeft ftco-animated');
							} else if ( effect === 'fadeInRight') {
								el.addClass('fadeInRight ftco-animated');
							} else {
								el.addClass('fadeInUp ftco-animated');
							}
							el.removeClass('item-animate');
						},  k * 50, 'easeInOutExpo' );
					});	
				}, 100);
			}
		} , { offset: '95%' } );
	};
	contentWayPoint();

	$('.image-popup').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		closeBtnInside: false,
		fixedContentPos: true,
		mainClass: 'mfp-no-margins mfp-with-zoom', // Class to remove default margin from left and right side
		 gallery: {
		  enabled: true,
		  navigateByImgClick: true,
		  preload: [0,1] // Will preload 0 before current and 1 after the current image
		},
		image: {
		  verticalFit: true
		},
		zoom: {
		  enabled: true,
		  duration: 300 // Don't forget to change the duration also in CSS
		}
	});

    $('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({
		disableOn: 700,
		type: 'iframe',
		mainClass: 'mfp-fade',
		removalDelay: 160,
		preloader: false,
		fixedContentPos: false
    });
   
    var goHere = function() {
		$('.mouse-icon').on('click', function(event){
			event.preventDefault();
			$('html,body').animate({
				scrollTop: $('#'+goHereSection).offset().top
			}, 500, 'easeInOutExpo');
			return false;
		});
    };
    goHere();
	
	var copyright = function() {
		const yearCopyright = document.getElementById('year');
		if (yearCopyright){
			yearCopyright.innerText = new Date().getFullYear();
		}		
	}
	copyright();
	
	$(".progress").each(function() {
		var value = $(this).attr('data-value');
		var left = $(this).find('.progress-left .progress-bar');
		var right = $(this).find('.progress-right .progress-bar');

		if (value > 0) {
		  if (value <= 50) {
			right.css('transform', 'rotate(' + percentageToDegrees(value) + 'deg)')
		  } else {
			right.css('transform', 'rotate(180deg)')
			left.css('transform', 'rotate(' + percentageToDegrees(value - 50) + 'deg)')
		  }
		}
	});
	document.querySelectorAll('.progress-bar').forEach(progressBar => {
		const valueNow = parseFloat(progressBar.getAttribute('aria-valuenow'));
		const valueMin = parseFloat(progressBar.getAttribute('aria-valuemin'));
		const valueMax = parseFloat(progressBar.getAttribute('aria-valuemax'));
		const widthPercentage = ((valueNow - valueMin) / (valueMax - valueMin)) * 100;
		progressBar.style.width = `${widthPercentage}%`;
	});	

    var TxtRotate = function(el, toRotate, period) {
	  this.toRotate = toRotate;
	  this.el = el;
	  this.loopNum = 0;
	  this.period = parseInt(period, 10) || 2000;
	  this.txt = '';
	  this.tick();
	  this.isDeleting = false;
    };
	TxtRotate.prototype.tick = function() {
		  var i = this.loopNum % this.toRotate.length;
		  var fullTxt = this.toRotate[i];

		  this.txt = this.isDeleting ? fullTxt.substring(0, this.txt.length - 1) : fullTxt.substring(0, this.txt.length + 1);
		  this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

		  var that = this;
		  var delta = 300 - Math.random() * 100;

		  if (this.isDeleting) { delta /= 2; }

		  if (!this.isDeleting && this.txt === fullTxt) {
			delta = this.period;
			this.isDeleting = true;
		  } else if (this.isDeleting && this.txt === '') {
			this.isDeleting = false;
			this.loopNum++;
			delta = 500;
		  }

		  setTimeout(function() { that.tick(); }, delta);
	};
	document.querySelectorAll('.txt-rotate').forEach(el => {
		var toRotate = el.getAttribute('data-rotate');
		var period = el.getAttribute('data-period');
		if (toRotate) {
		  new TxtRotate(el, JSON.parse(toRotate), period);
		}
	});
	
})(jQuery);

function initPage(){
	
  loadImages('.icon.svg','svg'); // Load SVG for all pages
 
  Object.keys(appRoutes).forEach(appRoute => { addRedirectById(appRoute) });
  
  initTranslator();

  const idPage = document.querySelector('head').id;
  
  if (idPage === 'index'){
	const navLinks = document.querySelectorAll('.nav-link');
	navLinks.forEach((navLink, index) => {
		navLink.href = `#${appAllSections[index]}`;
		appScrollSections.push($($(navLink).attr('href')));
		navLink.addEventListener('click', function (event) {
			event.preventDefault();
			// Check if the link is in subsections
			if ($(this).closest('#navi').length) {
				$('html, body').animate({
				  scrollTop: $($(this).attr('href')).offset().top - 180
				},500);
			}
			saveHashSession(appAllSections[index]);
		});
	});
	
	if (window.location.hash) {
		saveHashSession(window.location.hash.substring(1));
		clearUrlPath();
	}

	$(window).scroll(function(){
		// Retains the value of the scroll top with the reference at the middle of the page
		var scrollMiddle = $(this).scrollTop() + ($(window).height()/2);
		if ($(this).scrollTop() < 150){
			saveHashSession(homeSection);
		}
		for (let appScrollSection of appScrollSections) {
			var scrollStartZone = appScrollSection.offset().top;
			var scrollEndZone = scrollStartZone + appScrollSection.outerHeight();
			if (scrollMiddle >= scrollStartZone && scrollMiddle <= scrollEndZone){
				var scrolled_id = appScrollSection.attr('id') ?? homeSection;
				saveHashSession(scrolled_id);
			}	
		}
		if (scrolled_id !== checkpointSubSection && appSubSections.includes(scrolled_id)) {
		  checkpointSubSection = scrolled_id;
		  $('#navi a').removeClass('current').filter('[href="#' + checkpointSubSection + '"]').addClass('current');
		  saveHashSession(checkpointSubSection);
		}
	});

	loadImages('.logo-school', 'png');
	loadImages('.blog-img', 'avif');
	loadImages('.project.img','avif');
	loadImages('.articleImage', 'avif');
	
	const contactForm = document.querySelector("form[name='contactForm']");
	contactForm.addEventListener('submit', async (event) => { 
		event.preventDefault(); // Avoid Netlify default submission
		const formData = new FormData(event.target);
		try {
			await sendEmail(formData.get('name'), formData.get('subject'), formData.get('message'));
			if(window.location.protocol === "https:"){
				contactForm.submit(); // Submit form after sending the email
			}
		} catch (error) {
			return false;
		}
	});

  } else if (idPage === 'blog'){
		const articleShape = document.getElementById('articleShape'); 
		const iframeArticle = document.getElementById('iframeArticle');
		const hashLink = window.location.hash ? window.location.hash.substring(1) : '';
		const errorArticle = getMessage('error-generic');
		const host = window.location.origin;
		const currentHash = hashLink || sessionStorage.getItem('currentHash');
		
		if (!currentHash) {					 
		  articleShape.innerHTML = errorArticle;
		} else {
		   saveHashSession(currentHash);
		   clearUrlPath();				   
		   const urlArticle = `${host}/articles/${currentHash}_${getCurrentLanguage()}.html`;
		 
		   iframeArticle.src = urlArticle;
		 
		   iframeArticle.onload = () => {					 
				fetch(urlArticle)
				.then(response => response.text())
				.then(html => {													
					if(html.includes("It seems you've hit a broken link or the page has moved")){
						throw new Error("Resource not found"); // Catch directly to show error message when fetch redirects to 404 page
					}		
					
					const parser = new DOMParser();
					const doc = parser.parseFromString(html, 'text/html');
	 
					const header = doc.querySelector('.header');
					if (header) header.remove();
	 
					const footer = doc.querySelector('.footer');
					if (footer) footer.remove();
														
					articleShape.innerHTML =  doc.body.innerHTML + articleShape.innerHTML;
					loadImages('.articleImage','png');
					initProfile();
				})
				.catch(error => {
					articleShape.innerHTML = errorArticle;
				})
				.finally(() => {
					iframeArticle.remove();
				});
			}; 
	    }  
    }
}

/* Contact Form */

function gapiLoaded() {
	gapi.load('client', async () => { await gapi.client.init({
	  discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest'],
	}); });
}

function gisLoaded() {
	fetch("/.netlify/functions/env")
	.then(response => response.json())
	.then(variables => tokenClient = google.accounts.oauth2.initTokenClient({
	  client_id: variables.ENV_CLIENT_ID,
	  scope: 'https://www.googleapis.com/auth/gmail.send',
	  callback: (resp) => {
		if (resp.error !== undefined) {
		  throw resp;
		}
	  }
	}));
}

async function sendEmail(name, subject, message) {
	const email = [
		'From: me',
		'To: nicolas.bogalheiro@gmail.com',
		`Subject: ${subject}`,
		'',
		`${message}`,
		'----------------------------------------',
		`Message sent by ${name} (Portfolio)`,
	].join('\n');
	const successMessage = getMessage('success-generic');
	const errorMessage = getMessage('error-generic');
	const callbackForm = document.getElementById('callbackForm');
	callbackForm.innerText = '';

	// Base64 encode the email in URL-safe format
	const base64EncodedEmail = btoa(email)
		.replace(/\+/g, '-')
		.replace(/\//g, '_')
		.replace(/=+$/, '');

	// Check if token exists, otherwise request it
	let token = JSON.parse(localStorage.getItem('tokenAPI'));
	
	async function sendHelper(token) {
		const response = await fetch('https://www.googleapis.com/gmail/v1/users/me/messages/send', {
			method: 'POST',
			headers: {
				'Authorization': `${token.token_type} ${token.access_token}`,
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				raw: base64EncodedEmail
			})
		});

		if(response.ok){
			localStorage.setItem('tokenAPI', JSON.stringify(token));
			callbackForm.innerText = successMessage;
			if(window.location.protocol === "https:"){
				sessionStorage.clear();
			}
		} else{
			callbackForm.innerText = errorMessage;
			localStorage.clear();
		}
	}
	
	async function checkTokenConsent() {
	  return new Promise((resolve, reject) => {
		let interval = 3000;
		let maxRetries = 30 / (interval / 1000);
		let attempts = 0;

		let checkInterval = setInterval(async () => {
		  let tokenConsent = gapi.client.getToken();
		  if (tokenConsent) {
			clearInterval(checkInterval);
			await sendHelper(tokenConsent);
			resolve(tokenConsent);
		  } else if (++attempts >= maxRetries) {
			clearInterval(checkInterval);
			reject(new Error("Consent not given within 30 seconds"));
		  }
		}, interval);
	  });
	}
	
	if (!token) {
		callbackForm.innerText = '';
		// Request access token and wait for user consent with Google Identity Services
		try {
			tokenClient.requestAccessToken({prompt: 'consent'});
			await checkTokenConsent();
		} catch (error) {
			callbackForm.innerText = errorMessage;
			localStorage.clear();
		}
	} else {
		try {
			await sendHelper(token);
		} catch (error) {
			callbackForm.innerText = errorMessage;
			localStorage.clear();
		}
	}
}

function enableSubmitForm() {
  const submitButton = document.querySelector("input[type='submit']");
  const recaptchaResponse = grecaptcha.getResponse();
  submitButton.disabled = recaptchaResponse.length > 0 ? false : true;
}

function initCaptcha() {
	fetch("/.netlify/functions/env")
	  .then(response => response.json())
	  .then(variables => {
		grecaptcha.render('captchaCheck', {
		  'sitekey' : variables.SITE_RECAPTCHA_KEY,
		  'callback': enableSubmitForm
		});
	  })
	  .catch(error => { return false; });
};
