let xp = 4;
let cdiCount = 3;
let internshipsCount = 3;
let email = "nicolas.bogalheiro@gmail.com";
let city = "Lyon";
let certifsCount = 3;
let projectsCount = 20;
let experiencesCount = 5;
let countriesCount = 14;

let defaultRoutes = {
	"policy": "/{lng}/policy",
	"terms": "/{lng}/terms",
	"error404": "/404"
};

let appRoutes = {
  "index": "/{lng}",
  "blog": "/{lng}/blog",
  ...defaultRoutes
};

let homeSection = "home-section";
let goHereSection = "resume-section";
let blogSection = "blog-section";
let contactSection = "contact-section";

let appMainSections = [
  "about-section",
  "resume-section",
  "services-section",
  "projects-section",
  blogSection,
  contactSection
];

let appSubSections = [
  "education",
  "experiences",
  "skills",
  "languages",
  "awards"
];

let appSecondarySections = [
  "counter-section",
  "carousel-section"
];

let appAllSections = [
  homeSection,
  ...appMainSections,
  goHereSection,
  ...appSubSections,
  ...appSecondarySections
];

let appMessages = {
	"success-generic": {"fr": "L'opération a été un franc succès.", "en": "The operation was successfully completed."},
	"error-generic" : {"fr": "Oops ! Une erreur est survenue. Réessayez plus tard.", "en": "Oops ! An error has occurred. Try again later."}	
};

let tokenClient; // Generated by Google

let appScrollSections = []; // Completed automatically

let checkpointSubSection; // Completed automatically
 
function saveHashSession(hash) {
	sessionStorage.setItem('currentHash', hash);
}

function clearUrlPath() {
	history.replaceState(null, null, window.location.pathname);
}

function percentageToDegrees(percentage) {
	return percentage / 100 * 360;
}

function computeAge() {
	const d = new Date('1997-11-19');
	const today = new Date();
	return today.getFullYear() - d.getFullYear() - (today < new Date(today.getFullYear(), d.getMonth(), d.getDate()) ? 1 : 0);
}

function getCurrentRoute() {
  const path = window.location.pathname;
  return Object.keys(appRoutes).find(key => {
    const pattern = '^' + appRoutes[key].replace('{lng}', '[a-z]{2}') + '$';
    return new RegExp(pattern).test(path);
  }) || null;
}

function getCurrentLanguage() {
	return document.documentElement.lang;	
}

function toggleVisibility(selector, visibleClass = 'd-flex') {
    const $element = $(selector);
    if ($element.is('[hidden]') || $element.hasClass('d-none')) {
      $element.prop('hidden', false).removeClass('d-none').addClass(visibleClass);
    } else {
      $element.prop('hidden', true).removeClass(visibleClass);
    }
}

function getCurrentCompleteDate(){
	return new Date().toLocaleString();
}

function getCurrentDate(){
	return new Date().toLocaleDateString();
}

function lastCvUpdate(lang) {
	fetch("/.netlify/functions/env")
	  .then(response => response.json())
	  .then(variables => {
		const url = `https://api.github.com/repos/nicoboga4075/Portfolio/commits?path=docs/public/CV_${lang}.pdf&per_page=1`;
		fetch(url, {
		  headers: {
			'Authorization': `Bearer ${variables.GITHUB_API_TOKEN}`,
			'Accept': 'application/vnd.github+json'
		  }
		})
		.then(res => res.json())
		.then(data => {
		  if (data.length > 0) {
			const lastUpdate = data[0].commit.committer.date;
			lastUpdateDate.innerHTML = new Date(lastUpdate).toLocaleString();
		  } else {
			lastUpdateDate.innerHTML = getCurrentCompleteDate();
		  }
		})
	  })
	  .catch(error => { lastUpdateDate.innerHTML = getCurrentDate(); return false; });
}

function addRedirectById(elementId) {
  const balise = $('#' + elementId);
  if (balise) {
    const path = appRoutes[elementId];
    balise.attr('href', path ? path.replace('{lng}', getCurrentLanguage()) : '/en');
    balise.on('click', function() {
	  sessionStorage.clear(); // Reset hash for all other links
    });
  }
}

function loadImages(selector, extension, one = false) {
  const imgs = document.querySelectorAll(`${selector}`);
  Array.from(imgs).some((el, index) => {
	const locationImg = `images/${el.id}.${extension}`;
	if (el.tagName.toLowerCase() === 'img') {
		el.src = locationImg;
	} else {
		el.style.backgroundImage = `url(${locationImg})`;
	}
    // If first iteration, return true to stop further iteration
    return index === 0 && one;
  });
}

function loadBingo(){
	let timer = null;
	let number = 0;
	const target = 2713;
	const labelBtn = $('#bingoBtn').text();

	$('#bingoBtn').click(function() {
		if (number == 0) {
			$('#bingoTimer').removeClass();
			$('#bingoBtn').text('Stop');
			timer = setInterval(() => {
				number++;
				$('#bingoTimer').text(number);
			}, 10);
		} else {
			if (number == target) {
				$('#bingoTimer').addClass('victory');
			} else {
				$('#bingoTimer').addClass('defeat');
				$('#bingoBtn').text(labelBtn);
				clearInterval(timer);
				number = 0;
			}
		}
	});
}

function getMessage(key) {
	return appMessages[key]?.[`${getCurrentLanguage()}`] || '';
}

function switchLanguage(url) {
    try {
        const urlObj = new URL(url, window.location.origin);
        urlObj.pathname = urlObj.pathname.replace(/^\/(fr|en)/, (match) => {
            return match === '/fr' ? '/en' : '/fr';
        });
        const currentHash = sessionStorage.getItem('currentHash');
        if (currentHash && /^[a-zA-Z0-9-_]+$/.test(currentHash)) {
            urlObj.hash = `#${currentHash}`;
        } else {
            urlObj.hash = '';
        }
        return urlObj.pathname + urlObj.search + urlObj.hash;
    } catch (error) {
        return '/';
    }
}

function initTranslator() {
	const toggle = $('#language-toggle');
	if(toggle){
		toggle.prop('checked', getCurrentLanguage() == 'fr');
		toggle.on('change', function () {
			toggle.checked = getCurrentLanguage() == 'fr';
			const newUrl = switchLanguage(window.location.href);
			if (/^\/(?!\/)/.test(newUrl)) {
				window.location.href = newUrl;
			}
		});
	}
}

function initProfile() {
	$('.author').text($('meta[name="author"]').attr('content'));
	$('#city').text(city);
	$('.email').text(email);
	$('.age').text(computeAge());
	$('.xp').each(function() {
	  if ($(this).hasClass('number')) {
		$(this).attr('data-number', xp);
	  } else {
		$(this).text(xp);
	  }
	});
	$('#cdiCount').text(cdiCount);
	$('#experiences .resume-wrap a:first').addClass('victory');
	$('#certifsCount').attr('data-number', certifsCount);
	$('#projectsCount').attr('data-number', projectsCount);
	$('#experiencesCount').attr('data-number', experiencesCount);
	$('#countriesCount').attr('data-number', countriesCount);
}

function createCircularChart({canvasId, data, backgroundColor, labels, titles, subtitles, cutout = '50%'}) {
  const total = data.reduce((a, b) => a + b, 0);
  const currentLanguage = getCurrentLanguage();
  new Chart($('#' + canvasId)[0].getContext('2d'), {
    type: 'doughnut',
    data: {
	  labels: labels.map(label => {
          if (typeof label === 'string') return label;
		  return label[currentLanguage] || label.fr || label.en;
	  }),
      datasets: [{
        data: data,
        backgroundColor: backgroundColor,
        borderWidth: 0,
      }]
    },
    options: {
	  plugins: {
		  tooltip: {
            enabled: false
          },
		  title: {
            display: true,
            text: titles[currentLanguage] || titles.fr || titles.en,
            font: {
			  family: 'Poppins',
              size: 18,
              weight: 'bold'
            },
            padding: {
			  family: 'Poppins',
              top: 10,
              bottom: 20
            }
          },
		  subtitle: {
			  display: true,
			  text: subtitles[currentLanguage] || subtitles.fr || subtitles.en,
			  font: {
				family: 'Poppins',
				size: 14,
				weight: 'normal'
			  },
			  padding: {
				bottom: 15
			  }
		  },
		  legend: {
			position: 'bottom',
			align: 'center',
			labels: {
			  font: {
				  family: 'Poppins',
				  size: 13,
				  weight: '400'
			  },
			  boxWidth: 16,
              boxHeight: 16,
              padding: 14,
              usePointStyle: false,
              generateLabels: function(chart) {
                const data = chart.data;
                return data.labels.map((label, i) => {
                  const value = chart.data.datasets[0].data[i];
                  const percentage = ((value / total) * 100).toFixed(0);
                  return {
                    text: `${label} (${percentage}%)`,
                    fillStyle: chart.data.datasets[0].backgroundColor[i],
                    strokeStyle: '#fff',
                    lineWidth: 2
                  };
                });
			  }
			}
		  }
	  },
      cutout: cutout,
      responsive: true,
      animation: {
        animateRotate: true,
        duration: 2000,
        easing: 'easeInOutCubic'
      }
    }
  });
}

AOS.init({
  duration: 800,
  easing: 'slide'
});

(function($) {
	"use strict";
	
	$(window).stellar({
		responsive: true,
		parallaxBackgrounds: true,
		parallaxElements: true,
		horizontalScrolling: false,
		hideDistantElements: false,
		scrollProperty: 'scroll'
	});

	var fullHeight = function() {
		$('.js-fullheight').css('height', $(window).height());
		$(window).resize(function(){
			$('.js-fullheight').css('height', $(window).height());
		});
	};
	fullHeight();

	var loader = function() {
		setTimeout(function() { 
			if($('#ftco-loader').length > 0) {
				$('#ftco-loader').removeClass('show');
			}
		}, 1);
	};
	loader();

	$.Scrollax();

	var burgerMenu = function() {
		$('body').on('click', '.navbar-toggler', function(event){
			event.preventDefault();
			if ( $('#ftco-nav').is(':visible') ) {
				$(this).removeClass('active');
			} else {
				$(this).addClass('active');	
			}	
		});
	};
	burgerMenu();

	var onePageClick = function() {
		$(document).on('click', '#ftco-nav a[href^="#"]', function (event) {
			event.preventDefault();
			$('html, body').animate({
				scrollTop: $($.attr(this, 'href')).offset().top - 70
			}, 500);
		});
	};
	onePageClick();

	var carousel = function() {
		$(".owl-carousel").each(function(){
			var itemCount = $(this).children().length;
			$(this).owlCarousel({
				loop: true,
				autoplay: true,
				margin: 10,
				animateOut: 'fadeOut',
				animateIn: 'fadeIn',
				nav: true,
				autoplayHoverPause: false,
				items: 4,
				navText: ['<span class="icon-chevron-circle-left"></span>','<span class="icon-chevron-circle-right"></span>'],
				responsive: {
				  0:{
					items:Math.min(2, itemCount)
				  },
				  576:{
					items:Math.min(3, itemCount)
				  },
				  992:{
					items:Math.min(4, itemCount)
				  },
				  1200:{
					items:Math.min(5, itemCount)  
				  }
				}
			 });
		});
	};
	carousel();

	$('nav .dropdown').hover(function(){
		$(this).addClass('show');
		$(this).find('> a').attr('aria-expanded', true);
		$(this).find('.dropdown-menu').addClass('show');
	}, function(){
		$(this).removeClass('show');
		$(this).find('> a').attr('aria-expanded', false);
		$(this).find('.dropdown-menu').removeClass('show');
	});

	var scrollWindow = function() {
		$(window).scroll(function(){
			var $w = $(this), st = $w.scrollTop(), navbar = $('.ftco_navbar'), sd = $('.js-scroll-wrap');
			if (st > 150) {
				if ( !navbar.hasClass('scrolled') ) {
					navbar.addClass('scrolled');	
				}
			} 
			if (st < 150) {
				if ( navbar.hasClass('scrolled') ) {
					navbar.removeClass('scrolled sleep');
				}
			} 
			if ( st > 350 ) {
				if ( !navbar.hasClass('awake') ) {
					navbar.addClass('awake');	
				}
				if(sd.length > 0) {
					sd.addClass('sleep');
				}
			}
			if ( st < 350 ) {
				if ( navbar.hasClass('awake') ) {
					navbar.removeClass('awake');
					navbar.addClass('sleep');
				}
				if(sd.length > 0) {
					sd.removeClass('sleep');
				}
			}
			// For small screens, the header becomes dark
			if (window.scrollY <= 5) {
				$('.off').first().addClass('top-scroll');
			} else {
				$('.off').first().removeClass('top-scroll');
			}
		});
	};
	scrollWindow();

	var counter = function() {
		$('.ftco-about, .ftco-counter').waypoint( function( direction ) {
			if( direction === 'down' && !$(this.element).hasClass('ftco-animated') ) {
				var comma_separator_number_step = $.animateNumber.numberStepFactories.separator(',')
				$('.number').each(function(){
					var num = $(this).data('number');
					$(this).animateNumber(
					  {
					    number: num,
					    numberStep: comma_separator_number_step
					  }, 7000
					);
				});	
			}
		} , { offset: '95%' } );
	}
	counter();

	var contentWayPoint = function() {
		var i = 0;
		$('.ftco-animate').waypoint( function( direction ) {
			if( direction === 'down' && !$(this.element).hasClass('ftco-animated') ) {
				i++;
				$(this.element).addClass('item-animate');
				setTimeout(function(){
					$('body .ftco-animate.item-animate').each(function(k){
						var el = $(this);
						setTimeout( function () {
							var effect = el.data('animate-effect');
							if (effect === 'fadeIn') {
								el.addClass('fadeIn ftco-animated');
							} else if (effect === 'fadeInLeft') {
								el.addClass('fadeInLeft ftco-animated');
							} else if (effect === 'fadeInRight') {
								el.addClass('fadeInRight ftco-animated');
							} else {
								el.addClass('fadeInUp ftco-animated');
							}
							el.removeClass('item-animate');
						},  k * 50, 'easeInOutExpo' );
					});	
				}, 100);
			}
		} , { offset: '95%' } );
	};
	contentWayPoint();

	$('.image-popup').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		closeBtnInside: false,
		fixedContentPos: true,
		mainClass: 'mfp-no-margins mfp-with-zoom', // Class to remove default margin from left and right side
		 gallery: {
		  enabled: true,
		  navigateByImgClick: true,
		  preload: [0,1] // Will preload 0 before current and 1 after the current image
		},
		image: {
		  verticalFit: true
		},
		zoom: {
		  enabled: true,
		  duration: 300 // Don't forget to change the duration also in CSS
		}
	});

    $('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({
		disableOn: 700,
		type: 'iframe',
		mainClass: 'mfp-fade',
		removalDelay: 160,
		preloader: false,
		fixedContentPos: false
    });
   
    var goHere = function() {
		$('.mouse-icon').on('click', function(event){
			event.preventDefault();
			$('html,body').animate({
				scrollTop: $('#'+goHereSection).offset().top
			}, 500, 'easeInOutExpo');
			return false;
		});
    };
    goHere();
	
	var copyright = function() {
		const yearCopyright = $('#year');
		if (yearCopyright){
			yearCopyright.text(new Date().getFullYear());
		}		
	}
	copyright();
	
	$('.progress').each(function() {
		var value = $(this).attr('data-value');
		var left = $(this).find('.progress-left .progress-bar');
		var right = $(this).find('.progress-right .progress-bar');

		if (value > 0) {
		  if (value <= 50) {
			right.css('transform', 'rotate(' + percentageToDegrees(value) + 'deg)')
		  } else {
			right.css('transform', 'rotate(180deg)')
			left.css('transform', 'rotate(' + percentageToDegrees(value - 50) + 'deg)')
		  }
		}
	});
	$('.progress-bar').each(function(){
		const valueNow = parseFloat($(this).attr('aria-valuenow'));
		const valueMin = parseFloat($(this).attr('aria-valuemin'));
		const valueMax = parseFloat($(this).attr('aria-valuemax'));
		const widthPercentage = ((valueNow - valueMin) / (valueMax - valueMin)) * 100;
		$(this).css('width', `${widthPercentage}%`);
	});	

    var TxtRotate = function(el, toRotate, period) {
	  this.toRotate = toRotate;
	  this.el = el;
	  this.loopNum = 0;
	  this.period = parseInt(period, 10) || 2000;
	  this.txt = '';
	  this.tick();
	  this.isDeleting = false;
    };
	TxtRotate.prototype.tick = function() {
		  var i = this.loopNum % this.toRotate.length;
		  var fullTxt = this.toRotate[i];

		  this.txt = this.isDeleting ? fullTxt.substring(0, this.txt.length - 1) : fullTxt.substring(0, this.txt.length + 1);
		  this.el.html('<span class="wrap">'+this.txt+'</span>');

		  var that = this;
		  var delta = 300 - Math.random() * 100;

		  if (this.isDeleting) { delta /= 2; }

		  if (!this.isDeleting && this.txt === fullTxt) {
			delta = this.period;
			this.isDeleting = true;
		  } else if (this.isDeleting && this.txt === '') {
			this.isDeleting = false;
			this.loopNum++;
			delta = 500;
		  }

		  setTimeout(function() { that.tick(); }, delta);
	};
	$('.txt-rotate').each(function(){
		var toRotate = $(this).attr('data-rotate');
		var period = $(this).attr('data-period');
		if (toRotate) {
		  new TxtRotate($(this), JSON.parse(toRotate), period);
		}
	});
	
	$('[data-bs-toggle="tooltip"]').each(function() {
      new bootstrap.Tooltip(this);
    });
	
	initProfile();
	
})(jQuery);

function initPage(){
	
  loadImages('.icon.svg','svg'); // Load SVG for all pages

  $.each(appRoutes, function(appRoute) { 
	addRedirectById(appRoute);
  });
  
  initTranslator();

  $('.open-mfp').click(function() {
    const target = $(this).data('target');
    toggleVisibility(target);
  });

  $('.mfp-close').click(function() {
    const modalId = $(this).closest('.mfp')[0].id;
    toggleVisibility('#' + modalId);
  });
  
  $('.owl-menu').click(function() {
    const target = $(this).data('target');
	$('.owl-menu.active').removeClass('active');
	$(this).addClass('active');
	$('.owl-carousel').not(target).each(function() {
	  if (!$(this).hasClass('d-none')) {
		$(this).addClass('d-none');
	  }
	  $(this).removeClass('active');
	});
	$(target).removeClass('d-none').addClass('active');
	$(target).trigger('refresh.owl.carousel'); // To avoid glitch switching to other carousel
  });

  const idPage = getCurrentRoute();
  
  if (idPage === 'index'){
	fetch("/.netlify/functions/visit")
      .then(response => response.json())
      .then(data => {
		 $('#ftco-visitor').text(data.visits);
      })
      .catch(error => {
		 $('#ftco-visitor').text(error);
	  });
	$('.nav-link').each(function(index, navLink) {
		navLink.href = `#${appAllSections[index]}`;
		appScrollSections.push($($(navLink).attr('href')));
		navLink.addEventListener('click', function (event) {
			event.preventDefault();
			// Check if the link is in subsections
			if ($(this).closest('#navi').length) {
				$('html, body').animate({
				  scrollTop: $($(this).attr('href')).offset().top - 180
				},500);
			}
			saveHashSession(appAllSections[index]);
		});
	});
	
	if (window.location.hash) {
		saveHashSession(window.location.hash.substring(1));
		clearUrlPath();
	}

	$(window).scroll(function(){
		// Retains the value of the scroll top with the reference at the middle of the page
		var scrollMiddle = $(this).scrollTop() + ($(window).height()/2);
		if ($(this).scrollTop() < 150){
			$('a[href*="' + homeSection + '"]').addClass('active');
			saveHashSession(homeSection);	
		}
		for (let appScrollSection of appScrollSections) {
			var scrollStartZone = appScrollSection.offset().top;
			var scrollEndZone = scrollStartZone + appScrollSection.outerHeight();
			if (scrollMiddle >= scrollStartZone && scrollMiddle <= scrollEndZone){
				var scrolled_id = appScrollSection.attr('id') ?? homeSection;
				saveHashSession(scrolled_id);
			}	
		}
		if (scrolled_id !== checkpointSubSection && appSubSections.includes(scrolled_id)) {
		  checkpointSubSection = scrolled_id;
		  $('#navi a').removeClass('current').filter('[href="#' + checkpointSubSection + '"]').addClass('current');
		  saveHashSession(checkpointSubSection);
		}
	});

	loadImages('.logo-school', 'png');
	loadImages('.blog-img', 'avif');
	loadImages('.project.img','avif');
	loadImages('.articleImage', 'avif');	
		
	lastCvUpdate(getCurrentLanguage());
	
	createCircularChart({
	  canvasId: 'skillsChart',
	  data: [45, 25, 15, 10, 5],
	  backgroundColor: ['#3e64ff', '#FFA60E', '#8BC34A', '#DC143C', '#000'],
	  labels: ['Back-end', 'Front-end', {fr: 'Gestion de projet', en: 'Project management'}, 'Support', 'CI/CD'],
	  titles: {fr: 'Répartition du temps passé sur mes compétences', en: 'Time distribution across my skills'},
	  subtitles: {fr: 'Données basées sur + 4 années en activité', en: 'Data based on + 4 years in activity'}
    });

	$('form[name="contactForm"]').on('submit', async (event) => { 
		event.preventDefault(); // Avoid Netlify default submission
		const formData = new FormData(event.target);
		try {
			await sendEmail(formData.get('name'), formData.get('subject'), formData.get('message'));
			if(window.location.protocol === 'https:'){
				$(this).submit(); // Submit form after sending the email
			}
		} catch (error) {
			return false;
		}
	});

	loadBingo();

  } else if (idPage === 'blog'){
		
		$('a[href*="' + blogSection + '"]').addClass('active');
	  
		const articleShape = $('#articleShape'); 
		const iframeArticle = $('#iframeArticle');
		const hashLink = window.location.hash ? window.location.hash.substring(1) : '';
		const errorArticle = getMessage('error-generic');
		const host = window.location.origin;
		const currentHash = hashLink || sessionStorage.getItem('currentHash');
		
		if (!currentHash) {					 
		  articleShape.text(errorArticle);
		} else {
		   saveHashSession(currentHash);
		   clearUrlPath();				   
		   const urlArticle = `${host}/articles/${currentHash}_${getCurrentLanguage()}.html`;
		 
		   iframeArticle.prop('src', urlArticle);
		 
		   iframeArticle.on('load', function(){					 
				fetch(urlArticle)
				.then(response => response.text())
				.then(html => {													
					if(html.includes("It seems you've hit a broken link or the page has moved")){
						throw new Error("Resource not found"); // Catch directly to show error message when fetch redirects to 404 page
					}		
					
					const parser = new DOMParser();
					const doc = parser.parseFromString(html, 'text/html');
	 
					const header = doc.querySelector('.header');
					if (header) header.remove();
	 
					const footer = doc.querySelector('.footer');
					if (footer) footer.remove();
														
					articleShape.html(doc.body.innerHTML + articleShape.html());
					loadImages('.articleImage','png');
					initProfile();
				})
				.catch(error => {
					articleShape.text(errorArticle);
				})
				.finally(() => {
					iframeArticle.remove();
				});
			}); 
	    }  
    }
}

/* Contact Form */

function gapiLoaded() {
	gapi.load('client', async () => { await gapi.client.init({
	  discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest'],
	}); });
}

function gisLoaded() {
	fetch("/.netlify/functions/env")
	.then(response => response.json())
	.then(variables => tokenClient = google.accounts.oauth2.initTokenClient({
	  client_id: variables.ENV_CLIENT_ID,
	  scope: 'https://www.googleapis.com/auth/gmail.send',
	  callback: (resp) => {
		if (resp.error !== undefined) {
		  throw resp;
		}
	  }
	}));
}

async function sendEmail(name, subject, message) {
	const email = [
		'From: me',
		'To: nicolas.bogalheiro@gmail.com',
		`Subject: ${subject}`,
		'',
		`${message}`,
		'----------------------------------------',
		`Message sent by ${name} (Portfolio)`,
	].join('\n');
	const successMessage = getMessage('success-generic');
	const errorMessage = getMessage('error-generic');
	const callbackForm = $('#callbackForm');
	callbackForm.text('');

	// Base64 encode the email in URL-safe format
	const base64EncodedEmail = btoa(email)
		.replace(/\+/g, '-')
		.replace(/\//g, '_')
		.replace(/=+$/, '');

	// Check if token exists, otherwise request it
	let token = JSON.parse(localStorage.getItem('tokenAPI'));
	
	async function sendHelper(token) {
		const response = await fetch('https://www.googleapis.com/gmail/v1/users/me/messages/send', {
			method: 'POST',
			headers: {
				'Authorization': `${token.token_type} ${token.access_token}`,
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				raw: base64EncodedEmail
			})
		});

		if(response.ok){
			localStorage.setItem('tokenAPI', JSON.stringify(token));
			callbackForm.text(successMessage);
			if(window.location.protocol === 'https:'){
				sessionStorage.clear();
			}
		} else{
			callbackForm.text(errorMessage);
			localStorage.clear();
		}
	}
	
	async function checkTokenConsent() {
	  return new Promise((resolve, reject) => {
		let interval = 3000;
		let maxRetries = 30 / (interval / 1000);
		let attempts = 0;

		let checkInterval = setInterval(async () => {
		  let tokenConsent = gapi.client.getToken();
		  if (tokenConsent) {
			clearInterval(checkInterval);
			await sendHelper(tokenConsent);
			resolve(tokenConsent);
		  } else if (++attempts >= maxRetries) {
			clearInterval(checkInterval);
			reject(new Error("Consent not given within 30 seconds"));
		  }
		}, interval);
	  });
	}
	
	if (!token) {
		callbackForm.text('');
		// Request access token and wait for user consent with Google Identity Services
		try {
			tokenClient.requestAccessToken({prompt: 'consent'});
			await checkTokenConsent();
		} catch (error) {
			callbackForm.text(errorMessage);
			localStorage.clear();
		}
	} else {
		try {
			await sendHelper(token);
		} catch (error) {
			callbackForm.text(errorMessage);
			localStorage.clear();
		}
	}
}

function enableSubmitForm() {
  const submitButton = $('input[type="submit"]');
  const recaptchaResponse = grecaptcha.getResponse();
  submitButton.prop('disabled', recaptchaResponse.length > 0 ? false : true);
}

function initCaptcha() {
	fetch("/.netlify/functions/env")
	  .then(response => response.json())
	  .then(variables => {
		grecaptcha.render('captchaCheck', {
		  'sitekey' : variables.SITE_RECAPTCHA_KEY,
		  'callback': enableSubmitForm
		});
	  })
	  .catch(error => { return false; });
}
