default:
  tags:
    - windows-local

stages:
  - setup
  - build
  - test
  - sonar
  - teardown

status-job:
  stage: setup
  script:
    - powershell -ExecutionPolicy Bypass -File ./runner_status.ps1
  artifacts:
    expire_in: 1 day

build-job:
  stage: build
  script:
    - echo "Building..."
    - |
      if ($env:CI -eq "true") {
        echo "> npm ci"
        npm ci
      } else {
        echo "> npm install"
        npm install
      }
    - echo "Build done!"
  cache:
    key: npm-cache
    paths:
      - node_modules/
    policy: push 

test-job:
  stage: test
  script:
    - echo "Running Jest tests..."
    - npm run jest
    - echo "Running Playwright tests..."
    - npx playwright test *> $null -ErrorAction SilentlyContinue; if ($LASTEXITCODE -ne 0) { echo "No tests found, exiting with code 0" }
    - echo "Run done!"
  cache:
    key: npm-cache
    paths:
      - node_modules/
    policy: pull 
  coverage: '/All files\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+([\d\.]+)/'
  artifacts:
    reports:
      junit:
        - reports/jest/junit.xml
        - reports/playwright/junit.xml
    paths:
      - reports/jest/html/
      - reports/jest/coverage/
      - reports/playwright/html/
      - reports/playwright/test-results/
    expire_in: 1 week
    
sonar-job:
  stage: sonar
  dependencies:
    - test-job
  script:
    - echo "Running SonarCloud analysis..."
    - npx sonar-scanner "-Dsonar.token=$env:SONAR_TOKEN"
    - echo "Sonar analysis done!"

cleanup-job:
  stage: teardown
  script:
    - Get-ChildItem -Path "C:\GitLab-Runner\builds" -Recurse | Remove-Item -Force -Recurse
  artifacts:
    expire_in: 1 day