stages:
  - setup
  - build
  - test
  - teardown
  
status-job:
  stage: setup
  tags: 
    - windows-local
  script:
    - powershell -ExecutionPolicy Bypass -File ./runner_status.ps1
  artifacts:
   expire_in: 1 day  
  
build-job:
  stage: build
  tags: 
    - windows-local
  script:
    - echo "Building..."
    - |
      if ($env:CI -eq "true") {
        echo "> npm ci"
        npm ci
      } else {
        echo "> npm install"
        npm install
      }
    - echo "Build done!"
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 month

test-job:
  stage: test
  tags: 
    - windows-local
  script:
    - echo "Running Jest tests..."
    - npm run jest
    - echo "Running Playwright tests..."
    - npx playwright test > /dev/null 2>&1 || echo "No tests found, skipping..."
    - echo "Run done!"
  coverage: '/All files\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+([\d\.]+)/'
  artifacts:
    reports:
      junit:
      - reports/jest/junit.xml
      - reports/playwright/junit.xml
    paths:
      - reports/jest/html/
      - reports/jest/coverage/
      - reports/playwright/html/
      - reports/playwright/test-results/
    expire_in: 1 week
    
cleanup-job:
  stage: teardown
  tags:
    - windows-local
  script:
    - Get-ChildItem -Path "C:\GitLab-Runner\builds" -Recurse | Remove-Item -Force -Recurse
  artifacts:
    expire_in: 1 day 
    