[build]
  publish = "."
  command = "npm run build"  

[dev]
  port = 8888
  framework = "#static"
  publish = "."
  staticServerPort = 3999
	
[[context.production.plugins]]
  package = "netlify-plugin-minify-html"

  [context.production.plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = true
   
[[context.production.plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [context.production.plugins.inputs]
    fail_deploy_on_score_thresholds = "true"
	
  [context.production.plugins.inputs.settings]
    preset = "desktop"
	locale = "en"

  [context.production.plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.5
	best-practices = 0.5
	seo = 0.5
	pwa = 0
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/du-voc-de-dev_en.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/du-voc-de-dev_fr.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/mcs_en.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/mcs_fr.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/presentation_en.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/presentation_fr.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/sur-quels-criteres-choisir-une-agence-web_en.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/sur-quels-criteres-choisir-une-agence-web_fr.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/5-conseils-pour-un-nom-de-marque-parfait_en.html"
	
  [[context.production.plugins.inputs.audits]]
	path = "articles/5-conseils-pour-un-nom-de-marque-parfait_fr.html"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = ""
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "404"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "404/"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/blog"
  
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/blog/"

  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/blog"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/blog/"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/policy"
  
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/policy/"

  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/policy"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/policy/"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/terms"
  
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "fr/terms/"

  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/terms"
	
  [[context.production.plugins.inputs.audits]]
	url = "https://nicoboga.netlify.app"
	path = "en/terms/" 

[[redirects]]
  from = "/en"
  to = "/index_en.html"
  status = 200

[[redirects]]
  from = "/fr"
  to = "/index_fr.html"
  status = 200
  
[[redirects]]
  from = "/en/blog"
  to = "/blog_en.html"
  status = 200

[[redirects]]
  from = "/fr/blog"
  to = "/blog_fr.html"
  status = 200

[[redirects]]
  from = "/en/terms"
  to = "/terms_en.html"
  status = 200

[[redirects]]
  from = "/fr/terms"
  to = "/terms_fr.html"
  status = 200

[[redirects]]
  from = "/en/policy"
  to = "/policy_en.html"
  status = 200

[[redirects]]
  from = "/fr/policy"
  to = "/policy_fr.html"
  status = 200