[dev]
  port = 8888
  framework = "#static"
  publish = "."
  staticServerPort = 3999

[[redirects]]
  from = "/en"
  to = "/index_en"
  status = 200

[[redirects]]
  from = "/fr"
  to = "/index_fr"
  status = 200
  
[[redirects]]
  from = "/en/blog"
  to = "/blog_en"
  status = 200

[[redirects]]
  from = "/fr/blog"
  to = "/blog_fr"
  status = 200

[[redirects]]
  from = "/en/terms"
  to = "/terms_en"
  status = 200

[[redirects]]
  from = "/fr/terms"
  to = "/terms_fr"
  status = 200

[[redirects]]
  from = "/en/policy"
  to = "/policy_en"
  status = 200

[[redirects]]
  from = "/fr/policy"
  to = "/policy_fr"
  status = 200