sonar.projectKey=nicoboga4075_Portfolio
sonar.organization=nicoboga4075
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.tests=tests,cypress
sonar.javascript.lcov.reportPaths=reports/jest/coverage/lcov.info
sonar.junit.reportPaths=reports/jest/junit.xml,reports/playwright/junit.xml
sonar.exclusions=node_modules/**,reports/**,images/**,videos/**,fonts/**,**/.gitkeep,**/*.mp4
sonar.host.url=https://sonarcloud.io